import pandas as pd
import numpy as np

def label_candidates(candidates_df, gt_dict):
    """
    Labels candidate pairs based on the ground truth dictionary.
    candidates_df must contain 'source1_entity_id' and 'candidate_entity_id'.
    """
    labels = []
    for _, row in candidates_df.iterrows():
        s1 = row['source1_entity_id']
        cand = row['candidate_entity_id']
        labels.append(1 if cand in gt_dict.get(s1, set()) else 0)
    candidates_df['label'] = labels
    return candidates_df

def mine_hard_negatives(labeled_df, n_negatives_per_source=150000):
    """
    Mines hard negatives and samples them symmetrically (e.g. 150k from S2, 150k from S3).
    Ensures country distributions match the true candidate distributions.
    
    labeled_df must contain features generated by pair_features.py
    """
    positives = labeled_df[labeled_df['label'] == 1].copy()
    negatives = labeled_df[labeled_df['label'] == 0].copy()
    
    print(f"Total positives: {len(positives)}")
    print(f"Total negatives available: {len(negatives)}")
    
    # Identify specific hard negative groups
    # 1. same-name-different-address
    mask_hn_name = (negatives['feat_name_ratio'] > 0.85) & (negatives['feat_addr_ratio'] < 0.4)
    # 2. same-postal-different-business
    mask_hn_addr = (negatives['feat_addr_numbers_jaccard'] > 0.8) & (negatives['feat_name_ratio'] < 0.4)
    # 3. high-fuzzy-but-conflicting-address
    mask_hn_fuzzy = (negatives['feat_core_ratio'] > 0.7) & (negatives['feat_addr_ratio'] < 0.5)
    
    # 4. hard negatives specific to singleton S1 entities
    s1_with_pos = set(positives['source1_entity_id'].unique())
    mask_hn_singletons = ~negatives['source1_entity_id'].isin(s1_with_pos)
    
    # Create a column for priority sampling (higher is harder)
    negatives['hard_score'] = 0
    negatives.loc[mask_hn_name, 'hard_score'] += 2
    negatives.loc[mask_hn_addr, 'hard_score'] += 2
    negatives.loc[mask_hn_fuzzy, 'hard_score'] += 1
    negatives.loc[mask_hn_singletons, 'hard_score'] += 1
    
    # Add random noise to hard_score to break ties randomly but keep distribution
    np.random.seed(42)
    negatives['hard_score'] = negatives['hard_score'].astype(float) + np.random.uniform(0, 0.5, len(negatives))
    
    sampled_negatives = []
    
    # S2/S3 and Country symmetric sampling
    sources = ['S2', 'S3']
    for src in sources:
        is_src = negatives['feat_is_s2'] == 1 if src == 'S2' else negatives['feat_is_s3'] == 1
        src_negs = negatives[is_src]
        
        # Calculate target country proportions based on real candidate universe for this source
        country_counts = src_negs['country_s1'].value_counts(normalize=True)
        
        for country, prop in country_counts.items():
            target_n = int(n_negatives_per_source * prop)
            country_negs = src_negs[src_negs['country_s1'] == country]
            
            # Sort by hard_score descending to prioritize hard negatives, then take top target_n
            # This ensures we get the hardest negatives while maintaining the exact country/source distribution
            sampled = country_negs.sort_values(by='hard_score', ascending=False).head(target_n)
            sampled_negatives.append(sampled)
            
    final_negatives = pd.concat(sampled_negatives).drop(columns=['hard_score'])
    
    print(f"Sampled {len(final_negatives)} negatives.")
    
    # Final training set
    train_df = pd.concat([positives, final_negatives]).sample(frac=1.0, random_state=42).reset_index(drop=True)
    return train_df
